# Application-level secrets (not tied to a datastore).
# JWT signing secret: generated by Terraform, never seen by a human,
# injected into the container at runtime via Secrets Manager.

resource "random_password" "jwt_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "jwt" {
  name                    = "${var.project_name}-${var.environment}-jwt-secret"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id     = aws_secretsmanager_secret.jwt.id
  secret_string = random_password.jwt_secret.result
}
